apiVersion: batch/v1
kind: CronJob
metadata:
  name: jira-wiki-crawler
spec:
  schedule: "5 2 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: ghcr.io/eumel8/jira-scraper/jira-scraper:main
            env:
            - name: FULL_URL
              value: "https://wiki.example.com"
            - name: FULL_PREFIX
              value: "https://wiki.example.com/collector/pages.action?key=EXAMPLE"
            - name: SPACE_URL
          value: "https://wiki.example.com/pages/viewpage.action?spaceKey=EXAMPLE&title=Foo"
            volumeMounts:
            - mountPath: /data
              name: wiki-data
            - name: auth-json
              mountPath: /auth
              readOnly: true 
          restartPolicy: OnFailure
          volumes:
          - name: wiki-data
            persistentVolumeClaim:
              claimName: wiki-data
          - name: auth-json
            secret:
              secretName: auth-json
              items:
              - key: auth.json
                path: auth.json
