apiVersion: batch/v1
kind: CronJob
metadata:
  name: jira-wiki-crawler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: ghcr.io/eumel8/jira-scraper/jira-scraper:main
            env:
            - name: SPACE_URL
              value: "https://your-org.atlassian.net/wiki/spaces/DOC/overview"
            volumeMounts:
            - mountPath: /data
              name: wiki-data
            - name: auth-json
              mountPath: /auth
              readOnly: true 
          restartPolicy: OnFailure
          volumes:
          - name: wiki-data
            persistentVolumeClaim:
              claimName: wiki-data
          - name: auth-json
            secret:
              secretName: auth-json
              items:
              - key: auth.json
                path: auth.json
